config/routes.rb
Storytime::Application.routes.draw do
  resources :stories do 
    resources :pages
  end 
  resources :pages

  root 'welcome#index'

end

app/models/page.rb
class Page
  include Mongoid::Document
  belongs_to :story
  field :content, type: String
  field :number, type: Integer
end

app/models/story.rb
# models are ruby representations of what is in your db
class Story
	include Mongoid::Document
	field :title, type: String
	has_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @story = Story.find(params[:story_id])
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
      @page
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)
    @story = Story.find(params[:story_id])
    @page.story = @story
    

    respond_to do |format|
      if @page.save
        format.html { redirect_to @story, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page.story, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :content)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show  
    @story
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@story = Story.all.sample
		@page = Page.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="small-12 columns"> <!--   -->
        <%= link_to('Stories', stories_path, class: :button ) %>
        
      </div>
    </div>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for([@story, @page]) do |f| %>
      <%= f.label(:content) %>
      <%= f.text_area(:content) %>
      <%= f.submit class: :button %>
<% end %>

app/views/pages/edit.html.erb
<div class='row'>
	<div class='small-6 columns'>		
		<h1>Editing page</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @page %> |
		<%= link_to 'Back', story_path(@page.story) %>
	</div>
</div>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td>< % = link_to 'Show', page %></td>
        <td>< % = link_to 'Edit', edit_page_path(page) %></td>
        <td>< % = link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

< %= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<div class='row'>
	<div class='small-12 columns'>
		<h1>New page for <%= @story.title %></h1>
	</div>
</div>
<%= render 'form' %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

< %= link_to 'Edit', edit_page_path(@page) %> |
< %= link_to 'Back', pages_path %>

app/views/stories/_editform.html.erb
<%= form_for(@story) do |f| %>
	<%= f.label(:title, "#{@story[:title]}") %>
	<%= f.text_field(:title) %>
	<div class='small-12 columns'>
		<ul class='small-block-grid-2'>
			<% @story.pages.each do |page| %>
				<li>
					<div class='panel'>
						
						<p>
							<%= page.content %>
						</p>
						<%= link_to 'Edit', edit_story_page_path(@story, page) %>
					</div>
				</li>
			<% end %>
		</ul>
	<div class="actions">
		<%= f.submit class: :button %>
	</div>
<% end %>

app/views/stories/_form.html.erb
  <%= f.label(:title, 'What is our story called?') %>
  <%= f.text_field(:title) %>
  
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/stories/edit.html.erb
<div class='row'>
	<div class='small-12 columns'>
		
		<h1>Editing story</h1>
		<%= render 'editform' %>

		<%= link_to 'Show', @story %> |
		<%= link_to 'Back', stories_path %>
	</div>
</div>

app/views/stories/index.html.erb
<div class='row'>
    <div class='small-12 columns'>
        <h1>Listing stories</h1>
    </div>
</div>
<div class='row'>
    <div class="small-12 columns">
        <ul class='small-block-grid-2'>
            <% @stories.each do |story| %>
                <li>
                    <div class="panel">
                        <h3>
                            <%= story.title %>
                        </h3>
                        <hr />
                        <%= link_to 'Show', story %> | 
                        <%= link_to 'Edit', edit_story_path(story) %> |        
                        <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %>                    
                    </div>
                </li>
            <% end %>

        </ul>
    </div>
</div>
<hr />
<div class='row'>
    <div class='small-12 columns'>
        <%= link_to 'New Story', new_story_path, class: 'button' %>
    </div>
</div>

app/views/stories/new.html.erb
<div class='row'>
	<div class='small-6 columns'>
		<h1>New story</h1>
		<%= render 'form' %>

		<%= link_to 'Back', stories_path %>
	</div>
</div>

app/views/stories/show.html.erb
<div class='row'>
	<div class='small-12 columns'>
		<h1><%= @story.title %></h1>
	</div>
</div>

<div class='row'>
	<div class='small-12 columns'>
		<ul class='small-block-grid-2'>
			<% @story.pages.each do |page| %>
				<li>
						
						<div class='panel'>
							<p>
								<%= page.content %>
							</p>
						</div>
				</li>
			<% end %>
		</ul>
	</div>
</div>

<div class='row'>
	<div class='small-12 columns'>
		<%= link_to('New Page', new_story_page_path(@story), class: :button ) %>
		<%= link_to 'Edit', edit_story_path(@story), class: :button %>
		<%= link_to 'Back', stories_path, class: :button  %>
	</div>
</div>

app/views/welcome/index.html.erb
<div class='row'>
	<div class='small-12 columns'>
		<h1><%= @story.title %></h1>
		<ul class="small-block-grid-2">

			<% @story.pages.each do |page| %>
				<li>
					<div class="panel">
						<p>
							<%= page.content %>
						</p>
					</div>
				</li>
			<% end %>
		</ul>
	</div>
</div>
<div class='row'>
	<div class="small-12 columns">
		<%= form_for([@story, @page]) do |f| %>
			<%= f.label(:content) %>
			<%= f.text_area(:content) %>
			<%= f.submit('Add Page', class: :button) %>
		<% end %>
	</div>
</div>